/*********************************************************************
 * Name:      	main.cpp
 * Purpose:   	Implements simple wxWidgets application with GUI
 * 				created using wxFormBuilder.
 * Author:    
 * Created:   
 * Copyright: 
 * License:   	wxWidgets license (www.wxwidgets.org)
 * 
 * Notes:		Note that all GUI creation code is implemented in
 * 				gui.cpp source file which is generated by wxFormBuilder.
 *********************************************************************/

#include "main.h"

// initialize the application
IMPLEMENT_APP(MainApp);

////////////////////////////////////////////////////////////////////////////////
// application class implementation 
////////////////////////////////////////////////////////////////////////////////

bool MainApp::OnInit()
{
	SetTopWindow( new MainFrame( NULL ) );
	GetTopWindow()->Show();
	
	// true = enter the main loop
	return true;
}

////////////////////////////////////////////////////////////////////////////////
// main application frame implementation 
////////////////////////////////////////////////////////////////////////////////

MainFrame::MainFrame(wxWindow *parent) : MainFrameBase( parent )
{
}

MainFrame::~MainFrame()
{
}

void MainFrame::OnCloseFrame(wxCloseEvent& event)
{
	Destroy();
}

void MainFrame::OnExitClick(wxCommandEvent& event)
{
	Destroy();
}
        void MainFrame:: Tombol1( wxCommandEvent& event ){
        tampung.append("1");
        text_hasil->SetValue(tampung);
    }
		void MainFrame::Tombol2( wxCommandEvent& event ) {
        tampung.append("2");
        text_hasil->SetValue(tampung);
        }
		void MainFrame::Tombol3( wxCommandEvent& event ){
        tampung.append("3");
        text_hasil->SetValue(tampung);
        }
		void MainFrame::Tombol_tmb( wxCommandEvent& event ){
        bil1=stoi(tampung);
        tampung.clear();
        Tombol=tombol::tambah;
        }
		void MainFrame::Tombol4( wxCommandEvent& event ){
        tampung.append("4");
        text_hasil->SetValue(tampung);
        }
		void MainFrame::Tombol5( wxCommandEvent& event ){
            tampung.append("5");
            text_hasil->SetValue(tampung);
        }
		void MainFrame::Tombol6( wxCommandEvent& event ){
            tampung.append("6");
            text_hasil->SetValue(tampung);
        }
		void MainFrame::Tombol_kurang( wxCommandEvent& event ){
            bil1=stoi(tampung);
            tampung.clear();
            Tombol=tombol::kurang;
        }
		void MainFrame::Tombol7( wxCommandEvent& event ){
            tampung.append("7");
            text_hasil->SetValue(tampung);
        }
		void MainFrame::Tombol8( wxCommandEvent& event ){
            tampung.append("8");
            text_hasil->SetValue(tampung);
        }
		void MainFrame::Tombol9( wxCommandEvent& event ) {
            tampung.append("9");
            text_hasil->SetValue(tampung);
        }
		void MainFrame::Tombol_kali( wxCommandEvent& event ) {
            bil1=stoi(tampung);
            tampung.clear();
            Tombol=tombol::kali;
        }
		void MainFrame::Tombolc( wxCommandEvent& event ) {
            tampung.clear();
            text_hasil->SetValue("");
        }
		void MainFrame::Tombol0( wxCommandEvent& event ){
            tampung.append("0");
            text_hasil->SetValue(tampung);
        }
		void MainFrame::Tombol_samadengan( wxCommandEvent& event ){
            std::string shasil;
            bil2=stoi(tampung);
            tampung.clear();
            
            if(Tombol==tombol::tambah){
                hasil=bil1+bil2;
            }else if(Tombol==tombol::kurang){
                hasil=bil1-bil2;
            }else if(Tombol==tombol::kali){
                hasil=bil1*bil2;
            }else if(Tombol==tombol::bagi){
                hasil=bil1/bil2;
            }
            shasil=std::to_string(hasil);
            text_hasil->SetValue(shasil);
        }
		void MainFrame::Tombol_bagi( wxCommandEvent& event ){
        bil1=stoi(tampung);
        tampung.clear();
        Tombol=tombol::bagi;
        }
        
        void MainFrame::Even_menu_about( wxCommandEvent& event ){
            dialog_about *da=new dialog_about(this);
            da->Show(true);
        }